# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(582, 780)
        Form.setStyleSheet("QPushButton#PushButton{\n"
"    border-radius:25px;\n"
"}\n"
"")
        self.block = QtWidgets.QLabel(Form)
        self.block.setGeometry(QtCore.QRect(20, 10, 531, 731))
        self.block.setStyleSheet("border-image: url(:/images/background.jpeg);\n"
"border-radius: 20px;")
        self.block.setText("")
        self.block.setObjectName("block")
        self.icon = QtWidgets.QLabel(Form)
        self.icon.setGeometry(QtCore.QRect(140, 30, 281, 351))
        self.icon.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.icon.setStyleSheet("border-image: url(:/images/logo.png);")
        self.icon.setText("")
        self.icon.setObjectName("icon")
        self.alpla = QtWidgets.QLabel(Form)
        self.alpla.setGeometry(QtCore.QRect(20, 10, 531, 731))
        self.alpla.setStyleSheet("background-color:rgba(0, 0, 0, 20);")
        self.alpla.setText("")
        self.alpla.setObjectName("alpla")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(110, 490, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color:rgba(0, 0, 0, 40);\n"
"border: none;\n"
"border-bottom:2px solid  rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, 250);\n"
"padding-bottom: 7px; ")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 590, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.39801 rgba(32, 155, 77, 255), stop:0.716418 rgba(15, 60, 18, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"    color: rgb(200, 200, 200);\n"
"    border-radius:25px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.39801 rgba(52, 175, 97, 255), stop:0.716418 rgba(35, 80, 38, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color: rgb(134, 134, 134);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.username = QtWidgets.QLineEdit(Form)
        self.username.setGeometry(QtCore.QRect(110, 420, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setStyleSheet("background-color:rgba(0, 0, 0, 40);\n"
"border: none;\n"
"border-bottom:2px solid  rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, 230);\n"
"padding-bottom: 7px; ")
        self.username.setText("")
        self.username.setObjectName("username")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(190, 550, 221, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.block.raise_()
        self.alpla.raise_()
        self.password.raise_()
        self.username.raise_()
        self.icon.raise_()
        self.pushButton.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "L O G I N"))
        self.username.setPlaceholderText(_translate("Form", "User Name"))
        self.label.setText(_translate("Form", "INVALID PASSWORD"))
import rec_rc
